default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'abcdef' %>
  secret_token: 1234

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
